---
# playbook-real.yml

-
  name: Play01 - EC2 t2.medium fresh instance - Gather Information Before Setup
  # smartmetal.ai
  hosts: 54.68.53.75
  tasks:
    - name: Task0101 - Date, Time -- date
      command: date
    - name: Task0102 - Locate env (we need env for portable shebangs) -- which env
      command: which env
    - name: Task0103 - Locate bash (we use bash for everything) -- which bash
      command: which bash
    - name: Task0104 - System and Kernel Info -- uname -a
      command: uname -a
    - name: Task0105 - Proc Version -- cat /proc/version
      command: cat /proc/version
    - name: Task0106 - Process Table -- ps aux
      command: ps aux
    - name: Task0107 - Memory Stats -- vmstat
      command: vmstat
    - name: Task0108 - IO Stats -- iostat
      command: iostat
    - name: Task0109 - PATH -- echo "$PATH"
      command: echo "$PATH"
    - name: Task0110 - List Block Devices -- lsblk
      command: lsblk
    - name: Task0111 - Disk Freespace -- df -h
      command: df -h
    - name: Task0112 - List Filesystem Mount Points -- mount
      command: mount
    - name: Task0113 - List All System Limits (file descriptors, stack size, etc.) -- ulimit -a
      command: ulimit -a
    - name: Task0114 - Environment Variables -- env
      command: env

...

